"""add pending_edit_task_id to users

Revision ID: 61ddd59d9179
Revises: 9840cbf1e284
Create Date: 2026-03-21 21:27:47.422370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ddd59d9179'
down_revision: Union[str, None] = '9840cbf1e284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_edit_task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'tasks', ['pending_edit_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pending_edit_task_id')
    # ### end Alembic commands ###
