"""add pending_steps_task_id to users

Revision ID: 9840cbf1e284
Revises: 1b9fbc4561f9
Create Date: 2026-03-19 23:00:23.470646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9840cbf1e284'
down_revision: Union[str, None] = '1b9fbc4561f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_steps_task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'tasks', ['pending_steps_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'pending_steps_task_id')
    # ### end Alembic commands ###
